application: heebeegeebeehealers
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /register.*
  script: register.py

- url: /admin.*
  script: admin.py

- url: /camper.*
  script: camper_app.py

- url: /
  script: static.py

- url: .*html
  script: static.py
