application: heebeegeebeehealers
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /register.*
  script: register.py

- url: /
  script: static.py

- url: .*html
  script: static.py